apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
      interval: 12h
  values:
    admin:
      existingSecret: pihole-admin

    persistentVolumeClaim:
      enabled: true
      storageClass: nfs-csi-retain
      size: 2Gi
      accessModes:
         - ReadWriteOnce

    serviceDns:
      mixedService: true
      type: LoadBalancer
      loadBalancerIP: 10.77.1.202
      externalTrafficPolicy: Local

    serviceWeb:
      type: ClusterIP

    ingress:
      enabled: false

    extraEnvVars:
      TZ: America/Chicago
      FTLCONF_dns_upstreams: "10.77.1.1"

