apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
      interval: 12h
  values:
    admin:
      existingSecret: pihole-admin

    persistentVolumeClaim:
      enabled: true
      storageClass: nfs-csi-retain
      size: 2Gi
      accessModes:
         - ReadWriteOnce

    # --- DNS Service on LAN (MetalLB assigns this IP) ---
    serviceDns:
      mixedService: true
      type: LoadBalancer
      loadBalancerIP: 10.77.1.202
      externalTrafficPolicy: Local

    # --- Web UI Service (weâ€™ll expose via ingress) ---
    serviceWeb:
      type: ClusterIP

    ingress:
      enabled: false

    # --- Basic env ---
    extraEnvVars:
      TZ: America/Chicago
      FTLCONF_dns_upstreams: "10.77.1.1;8.8.8.8"

    # Optional but recommended: keep it stable on one node (so your PVC + networking are boring)
    # nodeSelector:
    #   kubernetes.io/hostname: k8s-worker-01

