apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pihole-ui
  namespace: pihole
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    kind: Gateway
  hostnames:
  - pihole.snyderhomelab.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: pihole-web
      port: 80

