apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pfsense-cert
  namespace: cert-manager
spec:
  secretName: pfsense-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - firewall.snyderhomelab.com
