apiVersion: v1
kind: Pod
metadata:
  name: vault-auth-test
  namespace: default
spec:
  serviceAccountName: demo-app
  containers:
  - name: vault
    image: hashicorp/vault:1.19.0
    command:
    - sleep
    - "3600"
    env:
    - name: VAULT_ADDR
      value: "http://vault.vault.svc.cluster.local:8200"

