        {"apiVersion":"storage.k8s.io/v1","kind":"CSIDriver","metadata":{"annotations":{},"name":"csi.san.synology.com"},"spec":{"attachRequired":true,"podInfoOnMount":true,"volumeLifecycleModes":["Persistent"]}}
    creationTimestamp: "2025-10-18T15:18:57Z"
    name: csi.san.synology.com
    resourceVersion: "335433"
    uid: fc8a8b63-ee7b-4dad-89e6-bb47f02b82e3
  spec:
    attachRequired: true
    fsGroupPolicy: ReadWriteOnceWithFSType
    podInfoOnMount: true
    requiresRepublish: false
    seLinuxMount: false
    storageCapacity: false
    volumeLifecycleModes:
    - Persistent
kind: List
metadata:
  resourceVersion: ""
