apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-csi-auth
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: synology-csi-auth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-info.yml: |
          clients:
            - host: 10.17.1.5
              port: 5001
              https: true
              username: {{ .username }}
              password: {{ .password }}
  data:
    - secretKey: password
      remoteRef:
        key: storage/synology-csi
        property: password
    - secretKey: username
      remoteRef:
        key: storage/synology-csi
        property: username
