apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi-repo
  namespace: synology-csi
spec:
  interval: 1h
  url: https://christian-schlichtherle.github.io/synology-csi-chart
