apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  chart:
    spec:
      chart: synology-csi
      sourceRef:
        kind: HelmRepository
        name: synology-csi-repo
  values:
    clientInfoSecret:
      name: synology-csi-auth
