apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"pod-security.kubernetes.io/enforce":"privileged"},"name":"synology-csi"}}
  creationTimestamp: "2025-10-18T15:18:57Z"
  labels:
    kubernetes.io/metadata.name: synology-csi
    pod-security.kubernetes.io/enforce: privileged
  name: synology-csi
  resourceVersion: "335423"
  uid: f646e4ca-33b7-48e2-b035-2535e739f3b6
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
