apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
provisioner: csi.san.synology.com
parameters:
  dsm: '10.17.1.5'
  location: '/volume1'
  fsType: 'ext4'
  protocol: 'iscsi'
  thinProvisioning: 'true'
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
# ---
# apiVersion: snapshot.storage.k8s.io/v1
# kind: VolumeSnapshotClass
# metadata:
#   name: synology-snapshot-class
# driver: csi.san.synology.com
# deletionPolicy: Delete
