---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-httproutes-from-all
  namespace: traefik
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: test-app
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: monitoring
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: vault
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: pihole
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: n8n
  to:
  - group: ""
    kind: Service

