apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: extrudelab-dev

resources:
  - ../../base

patches:
  - target:
      kind: HTTPRoute
      name: extrudelab-api
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: extrudelab-dev.snyderhomelab.com
