apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nas-cert
  namespace: cert-manager
spec:
  secretName: nas-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - file.snyderhomelab.com
