apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfd
  namespace: gpu-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
