apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: demo-app-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/apps/demo-app
        property: username
    - secretKey: password
      remoteRef:
        key: secret/apps/demo-app
        property: password
    - secretKey: api-key
      remoteRef:
        key: secret/apps/demo-app
        property: api-key
