apiVersion: v1
kind: Pod
metadata:
  name: eso-demo
  namespace: external-secrets
spec:
  serviceAccountName: default
  containers:
    - name: eso-demo
      image: "nginx"
      volumeMounts:
      - name: secret-volume
        mountPath: "/secrets"
        readOnly: true
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-app-secret
              key: username
  volumes:
    - name: secret-volume
      secret:
        secretName: demo-app-secret
        defaultMode: 0400
      
  
