apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ghcr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .ghcr-username }}",
                "password": "{{ .ghcr-password }}",
                "auth": "{{ printf "%s:%s" .ghcr-username .ghcr-password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: ghcr-username
      remoteRef:
        key: secret/apps/extrudelab
        property: ghcr-username
    - secretKey: ghcr-password
      remoteRef:
        key: secret/apps/extrudelab
        property: ghcr-password
