apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: extrudelab-api
  labels:
    app: extrudelab
    component: api
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    kind: Gateway
  hostnames:
  - "<update in overlay>"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: extrudelab-api
      port: 3000

