apiVersion: v1
kind: Service
metadata:
  name: extrudelab-api
  labels:
    app: extrudelab
    component: api
spec:
  type: ClusterIP
  selector:
    app: extrudelab
    component: api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
