---
apiVersion: source.tookkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 60m
  url: https://prometheus-community.github.io/helm-charts
