---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: snyderhomelab-wildcard-tls
  namespace: traefik
spec:
  secretName: snyderhomelab-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.snyderhomelab.com"
    - snyderhomelab.com
